---
title: "❤️ Nachbarschaftshilfe Augsburg"
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: nachbarschaftshilfe_augsburg@posteo.net
description: Solidarische Nachbarschaftshilfe in Zeiten von Corona. Der Plan ist in
  jedem Ortsteil Augsburgs einige junge gesunde Leute zu haben, die dort ein paar
  mal die Woche für Risiko-Menschen einkaufen.
baseurl: ''
url: ''
theme: minima
plugins:
- jekyll-feed
